Clear-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "https://br.gov.caixa.cns.applets.enviomensagem.class"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://caixa.gov.br/"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://www.caixa.gov.br/"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://conectividade.caixa.gov.br/"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "https://conectividade.caixa.gov.br/"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "https://conectividade.caixa.gov.br/registro/registrar.m? tkeut=2872728090006ea71ce431cdab2ab7afa7de75254a6ae07a6bb3a840cc18bb16e84dde9ded5e0a7f6a297fd244afa9f7d18a895b6474ff34f73760b1705597925732effb6d7c01ff952c3cb0b849f35b34f150e00fd86fa0732e962d673ffa190c323a3abd398a9f9898fe280cf84109dfafb761bda8f13f96e528a37c086fa2201402100955290&amp;ticketdata=20140210095529&amp;lcr=0"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://cmt.caixa.gov.br/"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://conectividade.caixa.gov.br:80/static/sicnsregistro/applet/assinar1.jar"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://conectividade.caixa.gov.br:80/static/cxpostal/applet/cnsenvio.jar"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://conectividade.caixa.gov.br:80/static/cxpostal/applet/msgenvio.jar"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "https://conectividade.caixa.gov.br/cxpostal/view/gepas/AppletDownload.jsp?qtdmsg=1"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "https://conectividade.caixa.gov.br/cxpostal/view/gepas/appletdownload.jar"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "https://conectividade.caixa.gov.br/cxpostal/view/gepas/appletdownload.jsp"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://conectividade.caixa.gov.br:80/static/cxpostal/applet/appdownload.jar"
Add-Content "$env:USERPROFILE\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites" "http://conectividade.caixa.gov.br:80/static/procuracao/applet/assinar.jar"